name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rust:

    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: 0
        submodules: recursive
    - name: Check code format
      run: cargo fmt -- --check
    - name: Check the package for errors
      run: cargo check --all
    - name: Lint rust sources
      run: cargo clippy --all-targets --all-features --tests --benches -- -D warnings
    - name:  Execute rust tests
      run: cargo test --all-features
